title: Kili Taylor
description: Welcome to my technical writing portfolio!

url: "https://gentle-rain-docs.github.io"
baseurl: "/technical-writing-portfolio"

author:
  name: Kili Taylor
  email: kili.taylor@protonmail.com
  
theme: minima

sass:
  style: compressed

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

permalink: /:title/

nav:
  - title: Home
    url: /
  - title: Writing Samples
    url: /writing-samples.html
  - title: Resume
    url: /resume.html

social:
  github: gentle-rain-docs
  linkedin: kilitaylor
